package com.mapbox.search.common

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

internal class IsoCountryCodeTest {

    @ParameterizedTest
    @MethodSource("allCountries")
    fun `Check countries and country code`(entry: Map.Entry<IsoCountryCode, String>) {
        val (inputValue, expectedValue) = entry

        assertEquals(expectedValue, inputValue.code)
        assertEquals(2, inputValue.code.length)
    }

    @Test
    fun `Check all country codes should be unique`() {
        val codeCountries = allCountries().map { it.value }
        val duplicates = codeCountries.groupingBy { it }.eachCount().filter { it.value > 1 }
        assertEquals(emptyMap<String, Int>(), duplicates)
    }

    private companion object {

        @JvmStatic
        fun allCountries(): Set<Map.Entry<IsoCountryCode, String>> = mapOf(
            IsoCountryCode.AFGHANISTAN to "af",
            IsoCountryCode.ALAND_ISLANDS to "ax",
            IsoCountryCode.ALBANIA to "al",
            IsoCountryCode.ALGERIA to "dz",
            IsoCountryCode.AMERICAN_SAMOA to "as",
            IsoCountryCode.ANDORRA to "ad",
            IsoCountryCode.ANGOLA to "ao",
            IsoCountryCode.ANGUILLA to "ai",
            IsoCountryCode.ANTARCTICA to "aq",
            IsoCountryCode.ANTIGUA_AND_BARBUDA to "ag",
            IsoCountryCode.ARGENTINA to "ar",
            IsoCountryCode.ARMENIA to "am",
            IsoCountryCode.ARUBA to "aw",
            IsoCountryCode.AUSTRALIA to "au",
            IsoCountryCode.AUSTRIA to "at",
            IsoCountryCode.AZERBAIJAN to "az",
            IsoCountryCode.BAHAMAS to "bs",
            IsoCountryCode.BAHRAIN to "bh",
            IsoCountryCode.BANGLADESH to "bd",
            IsoCountryCode.BARBADOS to "bb",
            IsoCountryCode.BELARUS to "by",
            IsoCountryCode.BELGIUM to "be",
            IsoCountryCode.BELIZE to "bz",
            IsoCountryCode.BENIN to "bj",
            IsoCountryCode.BERMUDA to "bm",
            IsoCountryCode.BHUTAN to "bt",
            IsoCountryCode.BOLIVIA to "bo",
            IsoCountryCode.BOSNIA_AND_HERZEGOVINA to "ba",
            IsoCountryCode.BOTSWANA to "bw",
            IsoCountryCode.BOUVET_ISLAND to "bv",
            IsoCountryCode.BRAZIL to "br",
            IsoCountryCode.BRITISH_INDIAN_OCEAN_TERRITORY to "io",
            IsoCountryCode.BRITISH_VIRGIN_ISLANDS to "vg",
            IsoCountryCode.BRUNEI to "bn",
            IsoCountryCode.BULGARIA to "bg",
            IsoCountryCode.BURKINA_FASO to "bf",
            IsoCountryCode.BURUNDI to "bi",
            IsoCountryCode.CAMBODIA to "kh",
            IsoCountryCode.CAMEROON to "cm",
            IsoCountryCode.CANADA to "ca",
            IsoCountryCode.CAPE_VERDE to "cv",
            IsoCountryCode.CARIBBEAN_NETHERLANDS to "bq",
            IsoCountryCode.CAYMAN_ISLANDS to "ky",
            IsoCountryCode.CENTRAL_AFRICAN_REPUBLIC to "cf",
            IsoCountryCode.CHAD to "td",
            IsoCountryCode.CHILE to "cl",
            IsoCountryCode.CHINA to "cn",
            IsoCountryCode.CHRISTMAS_ISLAND to "cx",
            IsoCountryCode.COCOS_ISLANDS to "cc",
            IsoCountryCode.COLOMBIA to "co",
            IsoCountryCode.COMOROS to "km",
            IsoCountryCode.CONGO_BRAZZAVILLE to "cg",
            IsoCountryCode.CONGO_KINSHASA to "cd",
            IsoCountryCode.COOK_ISLANDS to "ck",
            IsoCountryCode.COSTA_RICA to "cr",
            IsoCountryCode.COTE_DIVOIRE to "ci",
            IsoCountryCode.CROATIA to "hr",
            IsoCountryCode.CUBA to "cu",
            IsoCountryCode.CURACAO to "cw",
            IsoCountryCode.CYPRUS to "cy",
            IsoCountryCode.CZECHIA to "cz",
            IsoCountryCode.DENMARK to "dk",
            IsoCountryCode.DJIBOUTI to "dj",
            IsoCountryCode.DOMINICA to "dm",
            IsoCountryCode.DOMINICAN_REPUBLIC to "do",
            IsoCountryCode.ECUADOR to "ec",
            IsoCountryCode.EGYPT to "eg",
            IsoCountryCode.EL_SALVADOR to "sv",
            IsoCountryCode.EQUATORIAL_GUINEA to "gq",
            IsoCountryCode.ERITREA to "er",
            IsoCountryCode.ESTONIA to "ee",
            IsoCountryCode.ETHIOPIA to "et",
            IsoCountryCode.FALKLAND_ISLANDS_ to "fk",
            IsoCountryCode.FAROE_ISLANDS to "fo",
            IsoCountryCode.FIJI to "fj",
            IsoCountryCode.FINLAND to "fi",
            IsoCountryCode.FRANCE to "fr",
            IsoCountryCode.FRENCH_GUIANA to "gf",
            IsoCountryCode.FRENCH_POLYNESIA to "pf",
            IsoCountryCode.FRENCH_SOUTHERN_TERRITORIES to "tf",
            IsoCountryCode.GABON to "ga",
            IsoCountryCode.GAMBIA to "gm",
            IsoCountryCode.GEORGIA to "ge",
            IsoCountryCode.GERMANY to "de",
            IsoCountryCode.GHANA to "gh",
            IsoCountryCode.GIBRALTAR to "gi",
            IsoCountryCode.GREECE to "gr",
            IsoCountryCode.GREENLAND to "gl",
            IsoCountryCode.GRENADA to "gd",
            IsoCountryCode.GUADELOUPE to "gp",
            IsoCountryCode.GUAM to "gu",
            IsoCountryCode.GUATEMALA to "gt",
            IsoCountryCode.GUERNSEY to "gg",
            IsoCountryCode.GUINEA to "gn",
            IsoCountryCode.GUINEA_BISSAU to "gw",
            IsoCountryCode.GUYANA to "gy",
            IsoCountryCode.HAITI to "ht",
            IsoCountryCode.HEARD_AND_MCDONALD_ISLANDS to "hm",
            IsoCountryCode.HONDURAS to "hn",
            IsoCountryCode.HONG_KONG to "hk",
            IsoCountryCode.HUNGARY to "hu",
            IsoCountryCode.ICELAND to "is",
            IsoCountryCode.INDIA to "in",
            IsoCountryCode.INDONESIA to "id",
            IsoCountryCode.IRAN to "ir",
            IsoCountryCode.IRAQ to "iq",
            IsoCountryCode.IRELAND to "ie",
            IsoCountryCode.ISLE_OF_MAN to "im",
            IsoCountryCode.ISRAEL to "il",
            IsoCountryCode.ITALY to "it",
            IsoCountryCode.JAMAICA to "jm",
            IsoCountryCode.JAPAN to "jp",
            IsoCountryCode.JERSEY to "je",
            IsoCountryCode.JORDAN to "jo",
            IsoCountryCode.KAZAKHSTAN to "kz",
            IsoCountryCode.KENYA to "ke",
            IsoCountryCode.KIRIBATI to "ki",
            IsoCountryCode.KUWAIT to "kw",
            IsoCountryCode.KYRGYZSTAN to "kg",
            IsoCountryCode.LAOS to "la",
            IsoCountryCode.LATVIA to "lv",
            IsoCountryCode.LEBANON to "lb",
            IsoCountryCode.LESOTHO to "ls",
            IsoCountryCode.LIBERIA to "lr",
            IsoCountryCode.LIBYA to "ly",
            IsoCountryCode.LIECHTENSTEIN to "li",
            IsoCountryCode.LITHUANIA to "lt",
            IsoCountryCode.LUXEMBOURG to "lu",
            IsoCountryCode.MACAU to "mo",
            IsoCountryCode.MACEDONIA to "mk",
            IsoCountryCode.MADAGASCAR to "mg",
            IsoCountryCode.MALAWI to "mw",
            IsoCountryCode.MALAYSIA to "my",
            IsoCountryCode.MALDIVES to "mv",
            IsoCountryCode.MALI to "ml",
            IsoCountryCode.MALTA to "mt",
            IsoCountryCode.MARSHALL_ISLANDS to "mh",
            IsoCountryCode.MARTINIQUE to "mq",
            IsoCountryCode.MAURITANIA to "mr",
            IsoCountryCode.MAURITIUS to "mu",
            IsoCountryCode.MAYOTTE to "yt",
            IsoCountryCode.MEXICO to "mx",
            IsoCountryCode.MICRONESIA to "fm",
            IsoCountryCode.MOLDOVA to "md",
            IsoCountryCode.MONACO to "mc",
            IsoCountryCode.MONGOLIA to "mn",
            IsoCountryCode.MONTENEGRO to "me",
            IsoCountryCode.MONTSERRAT to "ms",
            IsoCountryCode.MOROCCO to "ma",
            IsoCountryCode.MOZAMBIQUE to "mz",
            IsoCountryCode.MYANMAR to "mm",
            IsoCountryCode.NAMIBIA to "na",
            IsoCountryCode.NAURU to "nr",
            IsoCountryCode.NEPAL to "np",
            IsoCountryCode.NETHERLANDS to "nl",
            IsoCountryCode.NEW_CALEDONIA to "nc",
            IsoCountryCode.NEW_ZEALAND to "nz",
            IsoCountryCode.NICARAGUA to "ni",
            IsoCountryCode.NIGER to "ne",
            IsoCountryCode.NIGERIA to "ng",
            IsoCountryCode.NIUE to "nu",
            IsoCountryCode.NORFOLK_ISLAND to "nf",
            IsoCountryCode.NORTHERN_MARIANA_ISLANDS to "mp",
            IsoCountryCode.NORTH_KOREA to "kp",
            IsoCountryCode.NORWAY to "no",
            IsoCountryCode.OMAN to "om",
            IsoCountryCode.PAKISTAN to "pk",
            IsoCountryCode.PALAU to "pw",
            IsoCountryCode.PALESTINE to "ps",
            IsoCountryCode.PANAMA to "pa",
            IsoCountryCode.PAPUA_NEW_GUINEA to "pg",
            IsoCountryCode.PARAGUAY to "py",
            IsoCountryCode.PERU to "pe",
            IsoCountryCode.PHILIPPINES to "ph",
            IsoCountryCode.PITCAIRN_ISLANDS to "pn",
            IsoCountryCode.POLAND to "pl",
            IsoCountryCode.PORTUGAL to "pt",
            IsoCountryCode.PUERTO_RICO to "pr",
            IsoCountryCode.QATAR to "qa",
            IsoCountryCode.REUNION to "re",
            IsoCountryCode.ROMANIA to "ro",
            IsoCountryCode.RUSSIA to "ru",
            IsoCountryCode.RWANDA to "rw",
            IsoCountryCode.SAMOA to "ws",
            IsoCountryCode.SAN_MARINO to "sm",
            IsoCountryCode.SAO_TOME_AND_PRINCIPE to "st",
            IsoCountryCode.SAUDI_ARABIA to "sa",
            IsoCountryCode.SENEGAL to "sn",
            IsoCountryCode.SERBIA to "rs",
            IsoCountryCode.SEYCHELLES to "sc",
            IsoCountryCode.SIERRA_LEONE to "sl",
            IsoCountryCode.SINGAPORE to "sg",
            IsoCountryCode.SINT_MAARTEN to "sx",
            IsoCountryCode.SLOVAKIA to "sk",
            IsoCountryCode.SLOVENIA to "si",
            IsoCountryCode.SOLOMON_ISLANDS to "sb",
            IsoCountryCode.SOMALIA to "so",
            IsoCountryCode.SOUTH_AFRICA to "za",
            IsoCountryCode.SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS to "gs",
            IsoCountryCode.SOUTH_KOREA to "kr",
            IsoCountryCode.SOUTH_SUDAN to "ss",
            IsoCountryCode.SPAIN to "es",
            IsoCountryCode.SRI_LANKA to "lk",
            IsoCountryCode.ST_BARTHELEMY to "bl",
            IsoCountryCode.ST_HELENA to "sh",
            IsoCountryCode.ST_KITTS_AND_NEVIS to "kn",
            IsoCountryCode.ST_LUCIA to "lc",
            IsoCountryCode.ST_MARTIN to "mf",
            IsoCountryCode.ST_PIERRE_AND_MIQUELON to "pm",
            IsoCountryCode.ST_VINCENT_AND_GRENADINES to "vc",
            IsoCountryCode.SUDAN to "sd",
            IsoCountryCode.SURINAME to "sr",
            IsoCountryCode.SVALBARD_AND_JAN_MAYEN to "sj",
            IsoCountryCode.SWAZILAND to "sz",
            IsoCountryCode.SWEDEN to "se",
            IsoCountryCode.SWITZERLAND to "ch",
            IsoCountryCode.SYRIA to "sy",
            IsoCountryCode.TAIWAN to "tw",
            IsoCountryCode.TAJIKISTAN to "tj",
            IsoCountryCode.TANZANIA to "tz",
            IsoCountryCode.THAILAND to "th",
            IsoCountryCode.TIMOR_LESTE to "tl",
            IsoCountryCode.TOGO to "tg",
            IsoCountryCode.TOKELAU to "tk",
            IsoCountryCode.TONGA to "to",
            IsoCountryCode.TRINIDAD_AND_TOBAGO to "tt",
            IsoCountryCode.TUNISIA to "tn",
            IsoCountryCode.TURKEY to "tr",
            IsoCountryCode.TURKMENISTAN to "tm",
            IsoCountryCode.TURKS_AND_CAICOS_ISLANDS to "tc",
            IsoCountryCode.TUVALU to "tv",
            IsoCountryCode.UGANDA to "ug",
            IsoCountryCode.UKRAINE to "ua",
            IsoCountryCode.UNITED_ARAB_EMIRATES to "ae",
            IsoCountryCode.UNITED_KINGDOM to "gb",
            IsoCountryCode.UNITED_STATES to "us",
            IsoCountryCode.URUGUAY to "uy",
            IsoCountryCode.US_OUTLYING_ISLANDS to "um",
            IsoCountryCode.US_VIRGIN_ISLANDS to "vi",
            IsoCountryCode.UZBEKISTAN to "uz",
            IsoCountryCode.VANUATU to "vu",
            IsoCountryCode.VATICAN_CITY to "va",
            IsoCountryCode.VENEZUELA to "ve",
            IsoCountryCode.VIETNAM to "vn",
            IsoCountryCode.WALLIS_AND_FUTUNA to "wf",
            IsoCountryCode.WESTERN_SAHARA to "eh",
            IsoCountryCode.YEMEN to "ye",
            IsoCountryCode.ZAMBIA to "zm",
            IsoCountryCode.ZIMBABWE to "zw"
        ).entries
    }
}
