#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH=$PWD
OUTPUT_PATH="${SCRIPT_PATH}/../MapboxSearch/ui/src/main/java/com/mapbox/search/ui/utils/maki/MakiToDrawableIdMapper.kt"
GENERATED_MAKI_OUTPUT_PATH="${SCRIPT_PATH}/maki/"
GENERATED_PNG_OUTPUT_SIZE_DP=20

echo "Downloading latest Maki"
pushd $TMPDIR > /dev/null
curl --silent -Lo maki.zip https://github.com/mapbox/maki/zipball/master

echo "Unzipping Maki.zip"
unzip -o maki.zip -d maki > /dev/null

echo "MakiToDrawableIdMapper.kt generation"

MAKI_ICONS_COUNT=$(find maki/*/icons -name "*-15.svg" | wc -l | xargs)
INITIAL_CAPACITY=$(expr $MAKI_ICONS_COUNT + $MAKI_ICONS_COUNT / 3 + 1)

cat <<EOF > "${OUTPUT_PATH}"
// This file was generated by '$(basename $0)' script
package com.mapbox.search.ui.utils.maki

import androidx.annotation.DrawableRes
import com.mapbox.search.ui.R

internal object MakiToDrawableIdMapper {

    private val makiIconsMap: Map<String, Int> by lazy {
        HashMap<String, Int>($INITIAL_CAPACITY).apply {
EOF

MAKI_ICON_PATHS=$(find maki/*/icons -name "*-15.svg" | sort)

i=0
for file in ${MAKI_ICON_PATHS}; do
    filefolder=$(dirname "$file")
    filename=$(basename "$file" -15.svg)
    filenameSnakeCase="${filename//-/_}"
    filenameLowerCase=$(echo "$filenameSnakeCase" | tr '[:upper:]' '[:lower:]')
    printf "            put(\"${filename}\", R.drawable.mapbox_search_sdk_ic_maki_${filenameLowerCase})" >> "${OUTPUT_PATH}"
    i=$((i+1))

    echo "" >> "${OUTPUT_PATH}"
done

cat <<EOF >> "${OUTPUT_PATH}"
        }
    }

    @DrawableRes
    fun getDrawableIdByMaki(maki: String?) = makiIconsMap[maki]
}
EOF

echo "SVG to larger SVG convertion"
generateSvgs() {
    if ! [ -x "$(command -v rsvg-convert)" ]; then
        echo -e '\033[93m\tSkipping SVGs convertion\033[0m: rsvg-convert is not installed.' >&2
        echo -e '\tInstallation: brew install librsvg' >&2
        return
    fi

    if ! [ -x "$(command -v convert)" ]; then
        echo -e '\033[93m\tSkipping SVGs convertion\033[0m: imagemagick is not installed.' >&2
        echo -e '\tInstallation: brew install imagemagick' >&2
        return
    fi

    for file in ${MAKI_ICON_PATHS}; do
        filefolder=$(dirname "$file")
        filename=$(basename "$file" -15.svg)

        # Skip if exists in "Custom maki/maki/${filename}.imageset"
        local CURRENT_ICON_IMAGESET_OUTPUT_PATH="${GENERATED_MAKI_OUTPUT_PATH}/"
        mkdir -p "${CURRENT_ICON_IMAGESET_OUTPUT_PATH}"
        local filenameSnakeCase="${filename//-/_}"
        local filenameLowerCase=$(echo "$filenameSnakeCase" | tr '[:upper:]' '[:lower:]')
        local output_path="${CURRENT_ICON_IMAGESET_OUTPUT_PATH}/mapbox_search_sdk_ic_maki_${filenameLowerCase}.svg"
        local heightSize=24
        rsvg-convert "${filefolder}/${filename}-15.svg" -f svg -h ${heightSize} -o "${output_path}"
    done
}

generateSvgs

echo "Done. Number of icons: $i"
echo "Now you need to visit https://inloop.github.io/svg2android/ to batch convert svg icons from folder /scripts/maki to android vector drawables"
echo "Do not forget to delete /scripts/maki folder after adding vector drawables to project"
