package com.mapbox.search.common.ev

import androidx.annotation.StringDef
import com.mapbox.annotation.MapboxExperimental

/**
 * OCPI TokenType.
 * Refer to this type in the [OCPI GitHub repository](https://github.com/ocpi/ocpi/blob/2.2.1/mod_tokens.asciidoc#mod_tokens_tokentype_enum)
 * for more details.
 */
@MapboxExperimental
public object EvseTokenType {

    /**
     * One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session
     * to a customer, probably an app user.
     */
    public const val AD_HOC_USER: String = "AD_HOC_USER"

    /**
     * Token ID generated by a server (or App.) to identify a user of an App.
     * The same user uses the same Token for every Session.
     */
    public const val APP_USER: String = "APP_USER"

    /**
     * RFID Token.
     */
    public const val RFID: String = "RFID"

    /**
     * Other type of token.
     */
    public const val OTHER: String = "OTHER"

    /**
     * Retention policy for the RoadObjectProvider
     */
    @Retention(AnnotationRetention.BINARY)
    @StringDef(
        AD_HOC_USER,
        APP_USER,
        RFID,
        OTHER,
    )
    public annotation class Type
}
