package com.mapbox.search.extensions

internal class QuerySelector {

    fun isEvQuery(query: String) = EV_KEYWORDS.contains(query.trim().lowercase())

    private companion object {
        val EV_KEYWORDS = mutableSetOf(
            "charging station",
            "charging stations",
            "charging point",
            "charging points",
            "electric vehicle charging station",
            "ev charging station",
            "ev charger",
            "ev connect charging station",
            "electric vehicle charging stations",
            "ev charging stations",
            "ev chargers",
            "ev connect charging stations",
            "ev charging",
            "ev",
            "evse",
            "electric vehicle supply equipment",
            "electric vehicle supply equipments",
            "borne de recharge",
            "bornes de recharge",
            "station de recharge",
            "stations de recharge",
            "station de charge",
            "stations de charge",
            "station de charge du véhicule électrique",
            "station de charge du vehicule electrique",
            "stations de charge du véhicule électrique",
            "stations de charge du vehicule electrique",
            "station de charge ev",
            "stations de charge ev",
            "ev chargeur",
            "ev chargeurs",
            "ev connexion station de charge",
            "ev connexion stations de charge",
            "oplaadpunt",
            "oplaadpunten",
            "laadpunt",
            "laadpunten",
            "laadpaal",
            "laadpalen",
            "laadstation voor elektrische voertuigen",
            "laadstations voor elektrische voertuigen",
            "ladestation für elektrofahrzeuge",
            "ladestationen für elektrofahrzeuge",
            "ladestation fur elektrofahrzeuge",
            "ladestationen fur elektrofahrzeuge",
            "ladestation",
            "ladestationen",
            "stromtankstelle",
            "stromtankstellen",
            "ladesäule",
            "ladesaule",
            "ladesäulen",
            "ladesaulen",
            "elektrofahrzeug-station",
            "elektrofahrzeug-stationen",
            "elektrofahrzeug station",
            "elektrofahrzeug stationen",
            "ev ladestation",
            "ev ladestationen",
            "ev-ladegerät",
            "ev ladegerät",
            "ev-ladegerat",
            "ev ladegerat",
            "ev-ladegeräte",
            "ev ladegeräte",
            "ev-ladegerate",
            "ev ladegerate",
            "la estación de carga",
            "vehículo eléctrico de estación",
            "la estación de carga ev",
            "cargador ev",
            "ev estación de carga de conexión",
            "stazione di ricarica",
            "veicolo elettrico stazione di ricarica",
            "ev stazione di ricarica",
            "caricabatterie ev",
            "ev connect stazione di ricarica",
            "nabíjecí stanice elektrických vozidel nabíjecí stanice",
            "stanice nabíjení ev",
            "ev nabíječka",
            "ev connect nabíjecí stanice",
            "ladestationen",
            "elektriske køretøjer opladning station",
            "ve ladestationen",
            "ev oplader",
            "ev connect ladestation",
            "σταθμό φόρτισης",
            "ο σταθμός φόρτισης ηλεκτρικών οχημάτων",
            "ev σταθμό φόρτισης",
            "φορτιστή ev",
            "ev connect σταθμό φόρτισης",
            "latausasema",
            "sähköauton latausasema",
            "ev latausasema",
            "ev laturi",
            "ev connect latausasema",
            "töltőállomás",
            "elektromos jármű töltőállomás",
            "ev töltőállomás",
            "ev töltő",
            "ev connect töltőállomás",
            "stacja ładowania elektrycznego",
            "stację ładowania pojazdu ev stacja ładowania",
            "ładowarka ev ev wtykowy stacja ładowania",
            "estação de carregamento",
            "veículo elétrico estação de carregamento",
            "ev estação de carregamento",
            "carregador de ev",
            "ev conexão estação de carregamento",
            "stație de încărcare",
            "vehicul electric stație de încărcare",
            "stație de încărcare ev",
            "încărcător ev",
            "ev stație de încărcare de conectare",
            "зарядная станция",
            "электрическое транспортное средство станции зарядки",
            "зарядная станция ev",
            "ev зарядного устройство",
            "е.в. подключения зарядной станции",
            "nabíjacia stanica elektrických vozidiel nabíjacej stanice",
            "stanice nabíjanie ev",
            "ev nabíjačka",
            "ev connect nabíjacej stanice",
            "laddningsstation",
            "elektriska fordon laddstationen",
            "ev laddningsstation",
            "ev laddare",
            "ev connect laddstationen",
            "şarj istasyonu",
            "şarj istasyonu elektrikli araç",
            "ev şarj istasyonu",
            "ev şarj cihazı",
            "ev bağlantı şarj istasyonu",
            "зарядна станція",
            "електричний транспортний засіб станції зарядки",
            "зарядна станція ev",
            "ev зарядного пристрою",
            "е.в. підключення зарядної станції",
            "ladestasjon",
            "elektrisk kjøretøy ladestasjon",
            "ev lader",
            "ev koble ladestasjonen",
            "punionica",
            "punionica za električna vozila",
            "punionica za ev",
            "stanica za punjenje",
            "postaja za punjenje",
            "ev punjač",
            "polnilnica",
            "polnilnica za električna vozila",
            "polnilnica za ev",
            "polnilna postaja za ev",
            "充電ステーション",
            "電気自動車充電ステーション",
            "ev充電ステーション",
            "ev充電器",
            "ev接続充電ステーション",
        )
    }
}